D8CORE-3050 Added path redirect import module
SU-SWS/stanford_profile pull request #362
Opened 2021-02-17 23:38 UTC by pookmish

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2021-02-22 16:47 UTC, imonroe requested changes
Looks like the patches here need to move; see also merge-conflict with composer.json

2021-02-22 16:47 UTC, imonroe commented on composer.json
> +            "drupal/path_redirect_import": {
should this be in the new `drupal-patches` module instead?

2021-02-24 17:52 UTC, imonroe commented
I'm trying to install this per the instructions, but composer won't resolve it to installable packages.  I've tried this with a fresh install of the `2.x` branch of acsf-cardinalsites, and it's still having problems.

```
  Problem 1
    - Root composer.json requires drupal/domain_301_redirect dev-2954889-d9-ready as 1.0.0, it is satisfiable by drupal/domain_301_redirect[dev-2954889-d9-ready] from vcs repo (git https://git.drupalcode.org/issue/domain_301_redirect-2954889) but drupal/domain_301_redirect[dev-1.x, 1.0.0-alpha0, 1.x-dev (alias of dev-1.x)] from composer repo (https://packages.drupal.org/8) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
  Problem 2
    - Root composer.json requires drupal/link_title_formatter dev-3174382-d9-ready as 1.1.0, it is satisfiable by drupal/link_title_formatter[dev-3174382-d9-ready] from vcs repo (git https://git.drupalcode.org/issue/link_title_formatter-3174382) but drupal/link_title_formatter[1.0.0, 1.1.0] from composer repo (https://packages.drupal.org/8) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
  Problem 3
    - Root composer.json requires drupal/paranoia dev-3148370-d9-ready as 1.9.0, it is satisfiable by drupal/paranoia[dev-3148370-d9-ready] from vcs repo (git https://git.drupalcode.org/issue/paranoia-3148370) but drupal/paranoia[dev-1.x, 1.0.0-alpha1, 1.x-dev (alias of dev-1.x)] from composer repo (https://packages.drupal.org/8) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
  Problem 4
    - Root composer.json requires drupal/response_code_condition dev-3141520-d9-ready as 1.0.0, it is satisfiable by drupal/response_code_condition[dev-3141520-d9-ready] from vcs repo (git https://git.drupalcode.org/issue/response_code_condition-3141520) but drupal/response_code_condition[dev-1.x, 1.0.0, 1.x-dev (alias of dev-1.x)] from composer repo (https://packages.drupal.org/8) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
  Problem 5
    - Root composer.json requires su-sws/stanford_profile dev-D8CORE-3050 -> satisfiable by su-sws/stanford_profile[dev-D8CORE-3050].
    - su-sws/stanford_profile dev-D8CORE-3050 requires drupal/domain_301_redirect ^1.0-alpha0 -> found drupal/domain_301_redirect[dev-1.x, 1.x-dev (alias of dev-1.x)] but it conflicts with your root composer.json require (dev-2954889-d9-ready as 1.0.0).
```

2021-02-26 16:56 UTC, pookmish commented
I updated the steps. it just requires a `--no-update` and then a full composer update to fix your issue.

2021-03-02 17:01 UTC, imonroe approved these changes
I got past the composer problems once I downgraded composer to 1.9.x.  Configs wouldn't import until I manually activated the module, but I'm not worried about that.  Got the configs imported and everything tests good.

2021-03-02 17:01 UTC, merged