D8CORE 5750
SU-SWS/stanford_profile pull request #532
Opened 2022-04-26 23:55 UTC by pookmish

- D8CORE-5750 Limit event cards to 1 taxonomy term
- D8CORE-5757 Add main content anchor links to term pages
- D8CORE-5759 Adjust display settings to properly format wysiwyg contents
- D8CORE-5760 Limit news and publication terms to 3 in card displays
- D8CORE-5767 Remove "Experimental" for basic page types
- D8CORE-5762 Update taxonomy descriptions
- D8CORE-5751 Update help text on three fields

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2022-04-28 16:30 UTC, imonroe commented
That also appears to be the case for teasers in card display: 
![image](https://user-images.githubusercontent.com/1263892/165800494-9229aabd-1565-40b5-b832-81062f37400c.png)

2022-04-28 16:35 UTC, imonroe requested changes
One small text change, and a question about why more than one term is showing on event cards

2022-04-28 17:58 UTC, pookmish commented
@imonroe what did you use when displaying those multiple terms? A list paragraph or teaser paragraph?

2022-04-28 17:58 UTC, pookmish commented on config/sync/field.field.node.stanford_publication.su_publication_topics.yml
> +description: 'Add all News Type terms for this article. Note: Only the top three selected terms will be displayed to the end-users. The complete list of terms will be displayed at the end of the arti
I'll make sure to copy and paste the correct language from the ticket.

2022-04-28 18:05 UTC, imonroe commented
The first example was a list paragraph, the second example was a teaser paragraph.  I was using the content from amtesting-test

2022-04-29 14:52 UTC, imonroe approved these changes
This works correctly with the fix implemented in https://github.com/SU-SWS/stanford_profile_helper/pull/198.  This is good to go once the help text update below is complete.

2022-04-29 15:34 UTC, pookmish commented on config/sync/field.field.node.stanford_publication.su_publication_topics.yml
> +description: 'Add all News Type terms for this article. Note: Only the top three selected terms will be displayed to the end-users. The complete list of terms will be displayed at the end of the arti
Ahh, I did copy the text from the ticket exactly. It is incorrect in the ticket. I believe your suggestion is correct..

2022-04-29 16:30 UTC, merged